<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6U5DIVL" failures="2" tests="2" name="Test" time="68.671" errors="0" timestamp="2024-02-24T22:19:37 IST">
  <testcase classname="testCases.TC_001_AccountRegistrationTest" name="verify_account_registration" time="21.134">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_001_AccountRegistrationTest.verify_account_registration(TC_001_AccountRegistrationTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verify_account_registration -->
  <testcase classname="testCases.TC_002_LoginTest" name="verify_login" time="25.68">
    <failure type="java.lang.AssertionError" message="Login failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login failed expected [true] but found [false]
at testCases.TC_002_LoginTest.verify_login(TC_002_LoginTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
</testsuite> <!-- Test -->
